hl.env('XCURSOR_SIZE', '36')
hl.env('XCURSOR_THEME', 'Nordzy-cursors-white')
hl.env('HYPRCURSOR_SIZE', '36')
hl.env('HYPRCURSOR_THEME', 'Nordzy-hyprcursors-white')
hl.env('GTK_IM_MODULE', 'fcitx')
hl.env('QT_IM_MODULE', 'fcitx')
hl.env('XMODIFIERS', '@im=fcitx')
hl.env('AQ_NO_MODIFIERS', '1')
