general {
  no_fade_in = true
  grace = 0
  disable_loading = true
}

background {
  monitor =
  path = /home/Michael/.config/hypr/background.png
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%H:%M:%S")"
  color = rgba(255, 255, 255, 0.85)
  font_size = 92
  font_family = Montserrat Thin
  position = 0, 120
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:60000] echo "$(date +"%A, %d %B" | tr '[:lower:]' '[:upper:]')"
  color = rgba(255, 255, 255, 0.55)
  font_size = 16
  font_family = Montserrat Light
  position = 0, 40
  halign = center
  valign = center
}

input-field {
  monitor =
  size = 320, 40
  outline_thickness = 2
  dots_size = 0.2
  dots_spacing = 0.3
  dots_center = true
  outer_color = rgba(255, 255, 255, 0.1)
  inner_color = rgba(0, 0, 0, 0.2)
  font_color = rgb(200, 200, 200)
  fade_on_empty = false
  placeholder_text = 
  hide_input = false
  
  check_color = rgba(255, 255, 255, 0.2)
  fail_color = rgba(255, 0, 0, 1.0)
  fail_text = 
  fail_timeout = 0
  fail_transition = 0
  
  position = 0, -60
  halign = center
  valign = center
}

label {
  monitor =
  text = $LAYOUT
  color = rgba(255, 255, 255, 0.4)
  font_size = 12
  font_family = Montserrat
  position = 0, -105
  halign = center
  valign = center
}



