{
  lib,
  pkgs,
  winapps-pkgs,
  ...
}:
let
  dprintPkgs = lib.filter (x: lib.isDerivation x) (lib.attrValues pkgs.dprint-plugins);
  tmuxPkgs = with pkgs.tmuxPlugins; [
    jump
    power-theme
    tmux-fzf
  ];
  nodePkgs = with pkgs.nodePackages_latest; [
    browser-sync
    live-server
    nodejs
    prettier
  ];
  python12Env = pkgs.python312.withPackages (
    ps: with ps; [
      cython
      debugpy
      django
      grip
      fastapi
      fastapi-cli
      fontforge
      nox
      nuitka
      numpy
      pandas
      pillow
      requests
    ]
  );
  python13Env = pkgs.python313.withPackages (
    ps: with ps; [
      cython
      debugpy
      django
      grip
      fastapi
      fastapi-cli
      fontforge
      nox
      nuitka
      numpy
      pandas
      pillow
      requests
    ]
  );
  winappsPkgs = with winapps-pkgs; [
    winapps
    winapps-launcher
  ];
in
{
  environment.systemPackages =
    dprintPkgs ++
    nodePkgs ++
    tmuxPkgs ++
    winappsPkgs ++
    (with pkgs; [
      acpi
      alacritty
      alejandra
      amdgpu_top
      ani-cli
      ansible
      ansifilter
      autologin
      basedpyright
      bash-language-server
      bc
      beamMinimal27Packages.elixir
      binutils
      biome
      black
      bluetui
      bluez
      brightnessctl
      btop
      byedpi
      bzip3
      cachix
      cargo
      chromium
      cl
      clang
      clang-tools
      clipse
      cmake
      code-cursor-fhs
      copyq
      cron
      csharp-ls
      dart
      dconf
      delve
      deno
      dig
      disko
      dmidecode
      docker-compose
      docker-compose-language-service
      dotnetCorePackages.sdk_9_0-bin
      dpkg
      dprint
      dua
      dust
      emmet-language-server
      emmet-ls
      entr
      eslint
      et
      evtest
      eww
      eza
      fastfetch
      fd
      ffmpeg
      file
      fish-lsp
      flatpak
      flutter
      fontforge
      fontforge-gtk
      fuzzel
      fzf
      gcc
      gdu
      ghostty
      ghc
      git-crypt
      glibc
      glibcLocales
      glow
      gnumake
      gnupg
      go
      godot_4
      goimports-reviser
      gopls
      gosimports
      grim
      gtk4
      haskell-language-server
      home-manager
      htmlhint
      htop
      hyprcursor
      hypridle
      hyprlang
      hyprlock
      hyprls
      hyprpaper
      hyprpicker
      hyprpolkitagent
      hyprshot
      hyprutils
      imagemagick
      imv
      iotop
      isort
      inkscape-with-extensions
      jdk
      jq
      kanata
      kubernetes
      keepass
      keyd
      kitty
      kotlin
      kotlin-language-server
      lazydocker
      lazygit
      lf
      libffi
      libnotify
      libreoffice
      lm_sensors
      lshw
      lua
      lua-language-server
      lynx
      mdcat
      memtester
      mongodb
      moreutils
      mpv
      mpvpaper
      neovide
      neovim
      niri
      nixd
      nixdoc
      nixfmt-rfc-style
      nix-init
      nix-serve
      nix-serve-ng
      nixos-rebuild-ng
      nixpkgs-fmt
      nix-tree
      nnn
      nordzy-cursor-theme
      nox
      ntfs3g
      nurl
      nushell
      obsidian
      obs-studio
      openssl
      oxlint
      pamixer
      pandoc
      pass
      pavucontrol
      perl
      php
      pipewire
      pkg-config
      playerctl
      polkit
      powershell
      pre-commit
      prismlauncher
      pv
      pyright
      python12Env
      python13Env
      python314
      pywal
      quickshell
      ranger
      redis
      ripdrag
      ripgrep
      rofi
      roslyn-ls
      rust-analyzer
      ryzenadj
      sass
      sddm-astronaut
      silver-searcher
      sing-box
      sing-geoip
      sing-geosite
      smartmontools
      spoofdpi
      sqlite
      sqlitebrowser
      sqls
      starship
      steam-run
      subversion
      superhtml
      tcpdump
      telegram-desktop
      tesseract
      terraform
      tg
      tlp
      tmux
      tree
      typescript
      typescript-language-server
      ueberzug
      ueberzugpp
      unciv
      universal-ctags
      unzip
      usbutils
      uutils-coreutils
      uutils-findutils
      uutils-diffutils
      vagrant
      v2ray
      video-downloader
      vim-language-server
      vscode-fhs
      w3m
      waydroid
      wev
      wget
      winetricks
      wineWowPackages.stagingFull
      wireplumber
      wl-clipboard
      wofi
      wtype
      xfce.thunar
      xplr
      xray
      yaml-language-server
      ytdownloader
      zapret
      zathura
      zig
      zip
      zlib
      zoxide
    ]);
}
