{
  inputs,
  pkgs,
  unstable-pkgs,
  freesmlauncher,
  system,
  ...
}:
let
  noctalia-shell = inputs.noctalia.packages.${system}.default;
  zen = inputs.zen-browser.packages.${system}.default;
  freesmlauncherPkg = freesmlauncher.packages.${system}.freesmlauncher;
  python13Env = pkgs.python313.withPackages (
    ps: with ps; [
      aiogram
      cython
      debugpy
      django
      grip
      fastapi
      fastapi-cli
      nox
      nuitka
      numpy
      pandas
      pillow
      psutil
      requests
      rich
      matplotlib
    ]
  );
  unstablePkgs = with unstable-pkgs; [
    browser-sync
    prettier
    distant
    uv
    steam-run
    telegram-desktop
    obsidian
    kdePackages.okular
    neovide
    neovim
    nodejs_latest
    sshfs-fuse
    lua-language-server
    luajitPackages.tree-sitter-cli
    unciv
    ruff
    ty
  ];
in
{
  environment = {
    systemPackages =
      unstablePkgs ++
      (with pkgs;
        [
          acpi
          atuin
          alacritty
          alejandra
          amberol
          amdgpu_top
          ani-cli
          ansible
          ansifilter
          autologin
          basedpyright
          bash-completion
          bash-language-server
          bc
          beamMinimal27Packages.elixir
          boxes
          binutils
          black
          blender
          blesh
          bluetui
          bluez
          brightnessctl
          btop
          bzip3
          cachix
          cargo
          copyq
          chromium
          cl
          clang
          clashtui
          clang-tools
          clipse
          cloudflare-warp
          cmake
          cron
          csharp-ls
          dconf
          devenv
          delve
          deno
          dig
          disko
          dmidecode
          docker-compose
          docker-compose-language-service
          dotnetCorePackages.sdk_9_0-bin
          dpkg
          dua
          dust
          emmet-language-server
          emmet-ls
          entr
          eslint
          et
          evtest
          eww
          eza
          fastfetch
          fd
          feishin
          ffmpeg
          foliate
          file
          fishPlugins.fifc
          fishPlugins.done
          fishPlugins.fzf
          fishPlugins.autopair
          fish-lsp
          flatpak
          fuzzel
          freesmlauncherPkg
          fzf
          gcc
          gdu
          ghostty
          gh
          ghc
          git-crypt
          gst_all_1.gst-libav
          gst_all_1.gst-plugins-bad
          gst_all_1.gst-plugins-good
          gst_all_1.gst-plugins-ugly
          gst_all_1.gst-plugins-base
          gst_all_1.gstreamer
          glab
          glibc
          glibcLocales
          glow
          gpu-screen-recorder
          gnumake
          gnupg
          go
          gogcli
          google-cloud-sdk
          goimports-reviser
          gopls
          gosimports
          grim
          gtk4
          grafana
          haskell-language-server
          haskellPackages.cabal-install
          home-manager
          htmlhint
          himalaya
          htop
          hyprcursor
          hypridle
          hyprlang
          hyprls
          hyprpaper
          hyprpicker
          hyprpolkitagent
          hyprshot
          hyprutils
          imagemagick
          imv
          iotop
          isort
          inkscape-with-extensions
          jdk
          jq
          kanata
          kubernetes
          keepass
          keyd
          killall
          kitty
          khal
          kooha
          kotlin
          kotlin-language-server
          lazydocker
          lazygit
          lf
          libva-utils
          libffi
          libfprint-tod
          libnotify
          libusb1
          libreoffice
          libsForQt5.qt5.qtgraphicaleffects
          lsyncd
          logrotate
          lm_sensors
          lsd
          lshw
          lua
          lynx
          kdePackages.dolphin
          kdePackages.kdialog
          kdePackages.xdg-desktop-portal-kde
          kdePackages.kio-admin
          kdePackages.kio-extras
          manix
          makemkv
          mdcat
          memtester
          minikube
          mongodb
          moreutils
          mc
          mpv
          mpvpaper
          networkmanagerapplet
          niri
          nixd
          nixdoc
          nixfmt
          nix-bash-completions
          nix-diff
          nix-index
          nix-init
          nix-output-monitor
          nix-serve
          nix-serve-ng
          nixos-rebuild-ng
          nixpkgs-fmt
          nix-tree
          nnn
          noctalia-shell
          nordzy-cursor-theme
          nox
          exfatprogs
          ntfsprogs-plus
          nurl
          nushell
          nvd
          obs-cli
          obs-cmd
          obs-studio
          opencode
          openssl
          oxlint
          pamixer
          pandoc
          pass
          pavucontrol
          perl
          php
          pipewire
          pkg-config
          playerctl
          polkit
          powershell
          prometheus
          pre-commit
          pv
          pyright
          python13Env
          pywal
          p7zip
          qbittorrent
          quickshell
          rar
          redis
          ripdrag
          ripgrep
          rofi
          roslyn-ls
          rust-analyzer
          ryzenadj
          sass
          sbc
          sddm-astronaut
          silver-searcher
          sing-box
          sing-geoip
          sing-geosite
          socat
          sops
          slurp
          ssh-to-age
          smartmontools
          speedtest-cli
          sqlite
          sqlitebrowser
          sqls
          starship
          statix
          subversion
          superhtml
          tauon
          tcpdump
          tesseract
          terraform
          tig
          tg
          tor-browser
          tlp
          tmux
          tree
          tshark
          typescript
          typescript-language-server
          udisks
          udiskie
          ueberzug
          ueberzugpp
          universal-ctags
          unrar
          unzip
          usbutils
          uutils-coreutils
          uutils-findutils
          uutils-diffutils
          vagrant
          ventoy-full
          video-downloader
          vim-language-server
          vlc
          vdirsyncer
          vscode-css-languageserver
          vscode-langservers-extracted
          vscode-json-languageserver
          vscode-fhs
          v2rayn
          w3m
          wev
          wget
          wifi-qr
          wireshark
          wireplumber
          wl-clipboard
          whisper-ctranslate2
          wofi
          wtype
          xdg-desktop-portal
          thunar
          xplr
          xray
          yaml-language-server
          ytdownloader
          yt-dlp
          ydotool
          zapret
          zathura
          zen
          zig
          zip
          zlib
          zbar
          zoxide
        ]
      );
  };
}
