{
  pkgs,
  ...
}:
{
  environment = {
    systemPackages = (
      with pkgs; [
        ansible
        autologin
        bash-completion
        bc
        binutils
        bluez
        cachix
        cron
        dconf
        dig
        disko
        dmidecode
        docker-compose
        evtest
        exfatprogs
        flatpak
        glibc
        glibcLocales
        gnupg
        gpu-screen-recorder
        grafana
        iotop
        kanata
        keyd
        killall
        libfprint-tod
        libffi
        libusb1
        lm_sensors
        logrotate
        lsyncd
        memtester
        nftables
        nix-serve
        nix-serve-ng
        nixos-rebuild-ng
        ntfsprogs-plus
        openssl
        pipewire
        pkg-config
        polkit
        prometheus
        redis
        ryzenadj
        smartmontools
        socat
        ssh-to-age
        tcpdump
        tlp
        tshark
        udisks
        usbutils
        wireshark
        wireplumber
        xdg-desktop-portal
        zapret
        zlib
        zsh
      ]
    );
  };
}
