general {
  gaps_in = 0
  gaps_out = 0
  border_size = 0
  col.active_border = rgba(66666610)
  col.inactive_border = rgba(aaaaaa05)
  resize_on_border = true
  allow_tearing = true
  layout = scrolling
}

gesture = 3, vertical, workspace

decoration {
  rounding = 0
  active_opacity = 1.0
  inactive_opacity = 1.0

  shadow {
  	enabled = true
    range = 300
    render_power = 1
    offset = 0 0
    scale = 0.8
  }

  blur {
    enabled = false
    ignore_opacity = true
    size = 8
    passes = 4
    noise = 0.03
    xray = true
    contrast = 1.8
  }
}


dwindle {
  pseudotile = true
  preserve_split = true
  smart_resizing = false
}


master {
  new_status = master
  orientation = center
  smart_resizing = false
}


misc { 
  force_default_wallpaper = 0
  disable_hyprland_logo = true
}


input {
  kb_layout = us,ru
  kb_options = grp:win_space_toggle
  follow_mouse = 1
  sensitivity = 0
  touchpad {
    natural_scroll = true
    tap-and-drag = true
    drag_lock = 0
    middle_button_emulation = true
    clickfinger_behavior = true
  }
}

gestures {
  workspace_swipe_touch = true
  workspace_swipe_direction_lock_threshold = 1
}

render {
  new_render_scheduling = true
  direct_scanout = true
}

scrolling {
  column_width = 1.0
  explicit_column_widths = 1.0
  focus_fit_method = 0
  follow_focus = true
}

bind = $mainMod, period, layoutmsg, move +col
bind = $mainMod, comma, layoutmsg, move -col

binde = $mainMod, equal, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1')
binde = $mainMod, minus, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float - 1')

cursor {
  no_hardware_cursors = false
  zoom_rigid = true
  zoom_factor = 1.0
}


