{ pkgs, winapps-pkgs, zen-browser-pkgs, ayugram-desktop-pkgs, ... }:
let
  nodePkgs = with pkgs.nodePackages_latest; [
    prettier
    live-server
    browser-sync
  ];
in
{
  environment.systemPackages = with pkgs; [
    fd
    uv
    lf
    cl
    go
    nh
    bc
    et
    imv
    gcc
    eza
    mpv
    zip
    fzf
    bat
    eww
    zig
    jdk
    lua
    php
    gdu
    dua
    wget
    tree
    dust
    xplr
    cron
    file
    nurl
    entr
    sass
    wofi
    acpi
    sqls
    nixd
    gtk4
    tmux
    zlib
    htop
    xray
    btop
    pass
    kitty
    glibc
    clang
    gopls
    cmake
    pywal
    bzip3
    bluez
    v2ray
    redis
    cargo
    disko
    biome
    unzip
    dconf
    polkit
    libffi
    oxlint
    ranger
    sqlite
    hyprls
    nixdoc
    clipse
    neovim
    nushell
    gnumake
    pamixer
    godot_4
    openssl
    blender
    ripgrep
    ghostty
    pyright
    nekoray
    hyprlock
    emmet-ls
    fish-lsp
    hyprlang
    waydroid
    nix-init
    starship
    nautilus
    spoofdpi
    sing-box
    powertop
    binutils
    neofetch
    obsidian
    hyprshot
    justbuild
    superhtml
    nodejs_23
    tesseract
    csharp-ls
    playerctl
    moreutils
    hyprpaper
    fastfetch
    memtester
    hyprutils
    alacritty
    hyprcursor
    obs-studio
    sing-geoip
    mongodb-ce
    powershell
    pre-commit
    vscode-fhs
    amdgpu_top
    ansifilter
    gosimports
    typescript
    pkg-config
    xfce.thunar
    imagemagick
    pavucontrol
    clang-tools
    ventoy-full
    sing-geosite
    wl-clipboard
    basedpyright
    glibcLocales
    rofi-wayland
    wl-clipboard
    brightnessctl
    python313Full
    rust-analyzer
    sqlitebrowser
    docker-compose
    zed-editor-fhs
    telegram-desktop
    nixfmt-rfc-style
    goimports-reviser
    nordzy-cursor-theme
    kdePackages.dolphin
    lua-language-server
    vim-language-server
    yaml-language-server
    bash-language-server
    winapps-pkgs.winapps
    libreoffice-qt6-fresh
    zen-browser-pkgs.generic
    beamMinimal27Packages.elixir
    winapps-pkgs.winapps-launcher
    docker-compose-language-service
    dotnetCorePackages.dotnet_9.sdk
    dockerfile-language-server-nodejs
    ayugram-desktop-pkgs.ayugram-desktop
    (python312.withPackages(ps: [ps.numpy ps.requests ps.pandas]))
  ] ++ nodePkgs;
}
