{
  lib,
  pkgs,
  ...
}:
let
  dprintPkgs = lib.filter (x: lib.isDerivation x) (lib.attrValues pkgs.dprint-plugins);
  nodePkgs = with pkgs.nodePackages_latest; [
    browser-sync
    live-server
    nodejs
    prettier
  ];
  python12Env = pkgs.python312.withPackages (
    ps: with ps; [
      cython
      django
      fastapi
      fastapi-cli
      nox
      nuitka
      numpy
      pandas
      pillow
      requests
    ]
  );
  python13Env = pkgs.python313.withPackages (
    ps: with ps; [
      cython
      django
      fastapi
      fastapi-cli
      nox
      nuitka
      numpy
      pandas
      pillow
      requests
    ]
  );
in
{
  environment.systemPackages =
    nodePkgs ++
    dprintPkgs ++
    (with pkgs; [
      acpi
      alacritty
      amdgpu_top
      ani-cli
      ansifilter
      autologin
      basedpyright
      bash-language-server
      bc
      beamMinimal27Packages.elixir
      binutils
      biome
      blender
      bluetui
      bluez
      brightnessctl
      btop
      byedpi
      bzip3
      cargo
      cachix
      cl
      clang
      clang-tools
      clipse
      cmake
      copyq
      cron
      dart
      dconf
      deno
      dig
      disko
      docker-compose
      docker-compose-language-service
      dockerfile-language-server-nodejs
      dotnetCorePackages.sdk_10_0-bin
      dprint
      dua
      dust
      emmet-language-server
      emmet-ls
      entr
      eslint
      et
      eww
      eza
      fastfetch
      fd
      file
      fish-lsp
      flutter
      fzf
      gcc
      gdu
      ghostty
      git-crypt
      glibc
      glibcLocales
      glow
      gnumake
      gnupg
      go
      godot_4
      goimports-reviser
      gopls
      gosimports
      grim
      gtk4
      helix
      home-manager
      htmlhint
      htop
      hyprcursor
      hyprlang
      hyprlock
      hyprls
      hyprpaper
      hyprpicker
      hyprshot
      hyprutils
      imagemagick
      imv
      jdk
      jq
      justbuild
      kdePackages.dolphin
      keepass
      kitty
      kotlin
      kotlin-language-server
      lazydocker
      lazygit
      lf
      libffi
      libreoffice-qt6-fresh
      lua
      lua-language-server
      lynx
      mdcat
      memtester
      mongodb-ce
      moreutils
      mpv
      nekoray
      neovim
      nh
      nix-init
      nix-tree
      nixd
      nixdoc
      nixfmt-rfc-style
      nnn
      nordzy-cursor-theme
      nox
      nurl
      nushell
      obs-studio
      obsidian
      openssl
      oxlint
      pamixer
      pandoc
      pass
      pavucontrol
      perl
      php
      pkg-config
      playerctl
      polkit
      powershell
      powertop
      pre-commit
      prismlauncher
      pv
      pyright
      python12Env
      python13Env
      pywal
      qutebrowser
      ranger
      redis
      ripgrep
      rofi-wayland
      roslyn-ls
      rust-analyzer
      sass
      sddm-astronaut
      silver-searcher
      sing-box
      sing-geoip
      sing-geosite
      smartmontools
      spoofdpi
      sqlite
      sqlitebrowser
      sqls
      starship
      subversion
      superhtml
      telegram-desktop
      tg
      tesseract
      tlp
      tmux
      tree
      typescript
      typescript-language-server
      ueberzug
      ueberzugpp
      unciv
      universal-ctags
      unzip
      uv
      v2ray
      video-downloader
      vim-language-server
      vscode-fhs
      w3m
      waydroid
      wev
      wget
      wine
      wl-clipboard
      wofi
      xfce.thunar
      xplorer
      xplr
      xray
      yaml-language-server
      ytdownloader
      zathura
      zed-editor-fhs
      zig
      zip
      zlib
      zoxide
    ]);
}
