{
  pkgs,
  inputs,
  system,
  ...
}:
let
  noctalia-shell = inputs.noctalia.packages.${system}.default;
  zen = inputs.zen-browser.packages.${system}.default;
  freesmlauncherPkg = inputs.freesmlauncher.packages.${system}.freesmlauncher;
  openclaw = inputs.nix-openclaw.packages.${system}.openclaw;
  python13Env = pkgs.python313.withPackages (
    ps:
      with ps; [
        aiogram
        cython
        debugpy
        django
        fastapi
        fastapi-cli
        grip
        matplotlib
        (lib.hiPrio nox)
        nuitka
        numpy
        pandas
        pillow
        psutil
        requests
        rich
      ]
  );
in
{
  home = {
    packages = (
      with pkgs; [
        acpi
        alacritty
        alejandra
        amberol
        amdgpu_top
        ani-cli
        ansifilter
        atuin
        bash-language-server
        bitwarden-desktop
        black
        blender
        blesh
        bluetui
        boxes
        brightnessctl
        browser-sync
        btop
        bzip3
        cargo
        chromium
        cl
        (lib.hiPrio clang)
        clang-tools
        cmake
        copyq
        csharp-ls
        delve
        deno
        devenv
        distant
        docker-compose-language-service
        dotnetCorePackages.sdk_9_0-bin
        dpkg
        dua
        dust
        emmet-language-server
        emmet-ls
        entr
        eslint
        et
        eww
        eza
        fastfetch
        fd
        feishin
        ffmpeg
        file
        foliate
        # freesmlauncherPkg
        fuzzel
        fzf
        gcc
        gdu
        gh
        ghostty
        git-crypt
        glab
        glow
        gnumake
        go
        gogcli
        goimports-reviser
        google-cloud-sdk
        gopls
        gosimports
        grim
        gst_all_1.gst-libav
        gst_all_1.gst-plugins-bad
        gst_all_1.gst-plugins-base
        gst_all_1.gst-plugins-good
        gst_all_1.gst-plugins-ugly
        gst_all_1.gstreamer
        gtk4
        himalaya
        htmlhint
        htop
        hyprcursor
        hypridle
        hyprlang
        hyprls
        hyprpicker
        hyprpolkitagent
        hyprutils
        imagemagick
        imv
        inkscape-with-extensions
        isort
        jdk
        jq
        kdePackages.dolphin
        kdePackages.kdialog
        kdePackages.kio-admin
        kdePackages.kio-extras
        kdePackages.okular
        kdePackages.xdg-desktop-portal-kde
        keepass
        khal
        kitty
        kooha
        (lib.hiPrio kubernetes)
        kdePackages.kwallet
        kdePackages.signon-kwallet-extension
        kdePackages.ksshaskpass
        kdePackages.kwalletmanager
        kdePackages.kwallet-pam
        lazydocker
        lazygit
        lf
        libnotify
        libreoffice
        libva-utils
        lsd
        lshw
        lua
        lua-language-server
        luajitPackages.tree-sitter-cli
        lynx
        mailspring
        manix
        mc
        mdcat
        minikube
        moreutils
        mpv
        mpvpaper
        neovide
        neovim
        networkmanagerapplet
        nix-bash-completions
        nix-diff
        nix-index
        nix-init
        nix-output-monitor
        nix-tree
        nixd
        nixdoc
        nnn
        noctalia-shell
        nodejs_latest
        nurl
        nushell
        nvd
        obs-cli
        obs-cmd
        obs-studio
        obsidian
        openclaw
        opencode
        oxlint
        p7zip
        pamixer
        pandoc
        pass
        pavucontrol
        perl
        php
        playerctl
        powershell
        pre-commit
        prettier
        pv
        python13Env
        pywal
        qt5.qtgraphicaleffects
        (lib.hiPrio rar)
        ripdrag
        ripgrep
        rofi
        roslyn-ls
        ruff
        rust-analyzer
        sass
        sbc
        silver-searcher-ng
        sing-box
        sing-geoip
        sing-geosite
        slurp
        sops
        speedtest-cli
        spice-gtk
        sqlite
        sqlitebrowser
        sqls
        sshfs-fuse
        starship
        statix
        steam-run
        subversion
        superhtml
        tauon
        telegram-desktop
        tesseract
        tg
        thunar
        tig
        tmux
        tor-browser
        tree
        ty
        typescript
        typescript-language-server
        udiskie
        ueberzugpp
        unciv
        universal-ctags
        unrar
        unzip
        uutils-coreutils
        uutils-diffutils
        uutils-findutils
        uv
        v2rayn
        vdirsyncer
        video-downloader
        vim-language-server
        virt-viewer
        vlc
        w3m
        wev
        wget
        wifi-qr
        wl-clipboard
        wofi
        wtype
        xplr
        xray
        yaml-language-server
        yt-dlp
        ytdownloader
        zathura
        zbar
        zen
        zig
        zip
        zoxide
      ]
    );
  };
}
